apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notify-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Jacarte/test_argocd'
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
